name: Simple Push Check

on: [push]

jobs: 
  check-file:
  runs-on: ubuntu-latest
  steps: 
    - uses: actions/checkout@v4
    - name: Say Hello
      run: echo "Hello from GITHUB Actions! The workload has run pee pee poo poo ."
    - name: List Files
      run: ls -la 
